import { expect, type APIRequestContext } from "@playwright/test";

import { SCOPE } from "./orchestration";

/**
 * The problem set, the host's own record, and the answer-reading this lane's
 * spec asserts on.
 *
 * Split out of `euler-live.spec.ts` for the reason `orchestration.ts` was split
 * out of the two specs it serves: what is a *gesture on the console* belongs
 * there and is shared by every lane, while what is a **read of this lane's
 * record** belongs here — the board rows, the transcript, the answers ledger,
 * and the table of problems whose answers are published.
 *
 * The card reads below deliberately duplicate a few lines of
 * `orchestration-live.spec.ts` rather than being hoisted into
 * `orchestration.ts`. That module states its own boundary at the top — console
 * gestures only, record reads belong beside the claim they settle — and moving
 * an HTTP read into it to save six lines would trade a stated design for a
 * de-duplication.
 */

/** A problem with a published answer, stated the way an operator would state it. */
export interface EulerProblem {
  /** The Project Euler number, which is also the key `PW_EULER_PROBLEM` takes. */
  id: string;
  /** The problem's published title, used in the goal and in the ledger row. */
  title: string;
  /**
   * The statement, in full.
   *
   * Handed over in the operator's message rather than fetched: this company
   * holds no `web` grant, so reading projecteuler.net is not a tool call away,
   * and a lane that let the lab browse for the statement would be testing its
   * browsing rather than its solving.
   *
   * That grant is not a network boundary and this lane does not pretend it is
   * — `shell` is granted and there is no sandbox
   * (`docs/spec/security/agent-isolation.md`). What makes the answer evidence
   * is `computed()` below: it has to have come out of a program that ran.
   */
  statement: string;
  /** The published answer, exactly. Compared as a string of digits. */
  answer: string;
  /** Why this one is in the set — what a run of it actually exercises. */
  why: string;
}

/**
 * The problems this lane can be pointed at.
 *
 * Chosen so that **the model's reasoning is the bottleneck and the CPU is
 * not**. Every one of them is settled by a program that finishes in seconds
 * once the right program is written; none needs a sieve to 10^9 or an hour of
 * compute. That is deliberate, and it is what makes a failure here legible: a
 * red run means the lab could not work out *what* to compute, which is the
 * claim under test, rather than that a sandbox timed out.
 */
export const EULER_PROBLEMS: Record<string, EulerProblem> = {
  // The default. Brute force is impossible by many orders of magnitude and the
  // structure is a Pell recurrence, but the first two solutions are given in
  // the statement and a third is findable by a short search — which is exactly
  // the shape the theorist's brief describes: compute the small cases, find the
  // pattern, state it as conjectured, and let the verifier attack it.
  "100": {
    id: "100",
    title: "Arranged probability",
    statement:
      "If a box contains twenty-one coloured discs, composed of fifteen blue discs and " +
      "six red discs, and two discs were taken at random, it can be seen that the " +
      "probability of taking two blue discs, P(BB) = (15/21) x (14/20) = 1/2.\n\n" +
      "The next such arrangement, for which there is exactly a 50% chance of taking two " +
      "blue discs at random, is a box containing eighty-five blue discs and thirty-five " +
      "red discs.\n\n" +
      "By finding the first arrangement to contain over 10^12 = 1,000,000,000,000 discs " +
      "in total, determine the number of blue discs that the box would contain.",
    answer: "756872327473",
    why: "no brute force exists; the answer comes from a recurrence found in small cases",
  },
  // A backtracking search over a small space. Cheap to run, and the trap is in
  // the statement rather than in the algorithm: the six numbers must be
  // cyclic, four-digit, and use each polygonal type exactly once.
  "61": {
    id: "61",
    title: "Cyclical figurate numbers",
    statement:
      "Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are " +
      "all figurate (polygonal) numbers and are generated by the following formulae:\n" +
      "  triangle    P(3,n) = n(n+1)/2\n" +
      "  square      P(4,n) = n^2\n" +
      "  pentagonal  P(5,n) = n(3n-1)/2\n" +
      "  hexagonal   P(6,n) = n(2n-1)\n" +
      "  heptagonal  P(7,n) = n(5n-3)/2\n" +
      "  octagonal   P(8,n) = n(3n-2)\n\n" +
      "The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three " +
      "interesting properties.\n" +
      "  1. The set is cyclic, in that the last two digits of each number is the first " +
      "two digits of the next number (including the last number with the first).\n" +
      "  2. Each polygonal type: triangle P(3,127)=8128, square P(4,91)=8281, and " +
      "pentagonal P(5,44)=2882, is represented by a different number in the set.\n" +
      "  3. This is the only set of 4-digit numbers with this property.\n\n" +
      "Find the sum of the only ordered set of six cyclic 4-digit numbers for which each " +
      "polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and " +
      "octagonal, is represented by a different number in the set.",
    answer: "28684",
    why: "a search whose difficulty is in reading the statement correctly, not in compute",
  },
  // The one where the naive loop *nearly* works: ten million chains is minutes
  // in Python and seconds once you notice only the digit multiset matters.
  // Costing the naive method is the whole exercise.
  "92": {
    id: "92",
    title: "Square digit chains",
    statement:
      "A number chain is created by continuously adding the square of the digits in a " +
      "number to form a new number until it has been seen before.\n\n" +
      "For example,\n" +
      "  44 -> 32 -> 13 -> 10 -> 1 -> 1\n" +
      "  85 -> 89 -> 145 -> 42 -> 20 -> 4 -> 16 -> 37 -> 58 -> 89\n\n" +
      "Therefore any chain that arrives at 1 or 89 will become stuck in an endless loop. " +
      "What is most amazing is that EVERY starting number will eventually arrive at 1 or 89.\n\n" +
      "How many starting numbers below ten million will arrive at 89?",
    answer: "8581146",
    why: "the naive loop is expensive and the reduction is a digit-multiset count",
  },
  // Brute force is 10^9 iterations — hours in Python, and the intended route is
  // a digit-position argument. The hardest of the set to reduce.
  "145": {
    id: "145",
    title: "How many reversible numbers are there below one-billion?",
    statement:
      "Some positive integers n have the property that the sum [ n + reverse(n) ] " +
      "consists entirely of odd (decimal) digits. For instance, 36 + 63 = 99 and " +
      "409 + 904 = 1313. We will call such numbers reversible; so 36, 63, 409, and 904 " +
      "are reversible. Leading zeroes are not allowed in either n or reverse(n).\n\n" +
      "There are 120 reversible numbers below one-thousand.\n\n" +
      "How many reversible numbers are there below one-billion (10^9)?",
    answer: "608720",
    why: "the naive loop cannot finish; the answer needs a per-digit-length argument",
  },
  // A small dynamic program. Here to be the easy rung when something else in
  // the lane is being debugged and the model's reasoning should not be the
  // variable.
  "191": {
    id: "191",
    title: "Prize strings",
    statement:
      "A particular school offers cash rewards to children with good attendance and " +
      "punctuality. If they are absent for three consecutive days or late on more than " +
      "one occasion then they forfeit the prize.\n\n" +
      "During an n-day period a trinary string is formed for each child consisting of " +
      "L's (late), O's (on time), and A's (absent).\n\n" +
      "Although there are eighty-one trinary strings that can be formed for a 4-day " +
      "period, exactly forty-three of them would lead to a prize.\n\n" +
      "How many prize strings exist over a 30-day period?",
    answer: "1918080160",
    why: "a three-state dynamic program — the rung to use when the lane itself is what is being debugged",
  },
};

/** Which problem this run is pointed at. `PW_EULER_PROBLEM`, default 100. */
export function chosenProblem(): EulerProblem {
  const key = (process.env.PW_EULER_PROBLEM || "100").trim();
  const problem = EULER_PROBLEMS[key];
  if (!problem) {
    throw new Error(
      `PW_EULER_PROBLEM=${key} names no problem in this lane's set. ` +
        `Known: ${Object.keys(EULER_PROBLEMS).join(", ")}. Add it to euler.ts with its ` +
        `published answer — a problem whose answer this lane does not know is a lane ` +
        `that cannot report pass or fail.`,
    );
  }
  return problem;
}

/** How many rounds of "carry on" the operator gives the lab. `PW_EULER_ROUNDS`. */
export const ROUNDS = Number.parseInt(process.env.PW_EULER_ROUNDS || "6", 10);

// ── The host's own record ──────────────────────────────────────────────────

/** One card on the board, as the host holds it. */
export interface Card {
  id: string;
  title: string;
  column: string;
  stage?: string;
  assignee?: string;
}

export async function allCards(request: APIRequestContext): Promise<Card[]> {
  const response = await request.get(`${SCOPE}/tasks`);
  expect(response.ok(), `listing cards failed: ${response.status()}`).toBeTruthy();
  const body = await response.json();
  return (body.tasks ?? body) as Card[];
}

/**
 * Where a card is, in the one vocabulary that covers every case: the stage when
 * it has one, the phase otherwise (`stage` is omitted for a pending or done
 * card — issue #1512).
 */
export function landing(card: Card): string {
  return card.stage ?? card.column;
}

/**
 * The landings a run has actually stopped in.
 *
 * An allow-list of *stopped* states rather than "anything but `in_progress`",
 * which is the trap `orchestration-live.spec.ts` documents: a card nobody has
 * dispatched reads `pending`, so the loose form counts work that never started
 * as work that finished.
 */
export const SETTLED = ["in_review", "paused", "done"];

/** Cards waiting for an operator to start them. */
export function pending(cards: Card[]): Card[] {
  return cards.filter((card) => landing(card) === "pending");
}

/** One message in the main line, as `GET {scope}/chat/history` serves it. */
export interface Message {
  author: string;
  text: string;
  mine: boolean;
}

/**
 * The main line's transcript, from the host rather than from the DOM.
 *
 * The console renders a long reply progressively and elides tool steps, so a
 * `textContent()` read races the transcript it is trying to quote. The journal
 * does not.
 */
export async function transcript(request: APIRequestContext): Promise<Message[]> {
  const response = await request.get(`${SCOPE}/chat/history`);
  expect(response.ok(), `reading the transcript failed: ${response.status()}`).toBeTruthy();
  return (await response.json()) as Message[];
}

/** The company's last word — the newest message the operator did not write. */
export async function lastCompanyMessage(request: APIRequestContext): Promise<Message | undefined> {
  const messages = await transcript(request);
  return [...messages].reverse().find((message) => !message.mine);
}

/** One row of a ledger, as `GET {scope}/ledgers/<slug>` serves it. */
export interface Entry {
  id: string;
  status: string;
  title: string;
  fields: Record<string, string>;
}

/**
 * The rows of one ledger, or `[]` when the company has no such ledger.
 *
 * Tolerant on purpose: the answers ledger is *observed* by this lane and never
 * asserted on. Whether the lab filed its bookkeeping is worth reporting beside
 * the verdict, but a run that reached the right number and forgot to write it
 * down has still solved the problem, and a lane that failed it for that would
 * be measuring diligence rather than capability.
 */
export async function ledgerEntries(
  request: APIRequestContext,
  slug: string,
): Promise<Entry[]> {
  const response = await request.get(`${SCOPE}/ledgers/${slug}`);
  if (!response.ok()) return [];
  const body = await response.json();
  return ((body.entries ?? []) as Entry[]) ?? [];
}

// ── Reading a number out of a sentence ─────────────────────────────────────

/**
 * Every integer in a piece of text, with separators stripped.
 *
 * The lab is asked for a bare integer and usually gives one, but a model that
 * writes "756,872,327,473" or "**756872327473**" has answered correctly and a
 * comparison that missed it would be reporting on formatting. Thousands
 * separators are removed only when they are grouped as such, so a list like
 * "1, 2, 3" stays three numbers rather than becoming one.
 */
export function integersIn(text: string): string[] {
  // Grouped separators only: `\d{1,3}(,\d{3})+` accepts 756,872,327,473 and
  // leaves "1, 2, 3" as the three numbers it is.
  const found = text.match(/\d{1,3}(?:,\d{3})+|\d+/g) ?? [];
  return found.map((token) => token.replace(/,/g, ""));
}

/** Whether a piece of text states `answer` as one of its numbers. */
export function states(text: string, answer: string): boolean {
  return integersIn(text).includes(answer);
}

// ── The operator's other job: answering approvals ──────────────────────────

/** One parked approval, as `GET {scope}/approvals` serves it. */
export interface Approval {
  id: string;
  /** The parked effect's dotted kind — `shell`, `run_workflow`, `record_entry`. */
  kind: string;
}

/**
 * Everything waiting on the operator right now.
 *
 * This lane cannot run without it, and finding that out is the most useful
 * thing its first run produced. The math-lab agreement explicitly calls
 * `request_approval` before `shell` or `run_workflow`, then waits; policy HITL
 * itself is disabled. So the parked card proves the agent followed the routed
 * computation boundary rather than relying on a host interception.
 *
 * So a lab that computes cannot be unattended, and a spec that only sent
 * messages was testing a company with one hand tied. The first run of this lane
 * passed anyway — the orchestrator was refused `shell` and `run_workflow`, did
 * the arithmetic in its own head, and got the published answer, which is
 * exactly the outcome `computed()` below now refuses to accept.
 */
export async function parked(request: APIRequestContext): Promise<Approval[]> {
  const response = await request.get(`${SCOPE}/approvals`);
  if (!response.ok()) return [];
  return (await response.json()) as Approval[];
}

/**
 * Approves everything parked, and reports what was approved.
 *
 * The operator's gesture, and an honest one to automate here: this company
 * holds no `web`, no `search` and no money-spending tool, so the only thing it
 * can ask permission for is to run a program in its own sandbox — which is the
 * work that was asked for. Nothing is ever denied; a lane that denied would be
 * testing the refusal path, which is a different spec.
 *
 * `detach` matters. Without it the POST holds open for the whole follow-up
 * turn — minutes, on a reasoning rung — and the poll that called it would time
 * out waiting on the thing it just authorised. Detached, the verdict is durable
 * when this returns and the continuation arrives on the event stream.
 */
export async function approveAll(request: APIRequestContext): Promise<string[]> {
  const waiting = await parked(request);
  const approved: string[] = [];
  for (const approval of waiting) {
    const response = await request.post(`${SCOPE}/approvals/${approval.id}`, {
      data: { verdict: "approve", detach: true },
    });
    if (response.ok()) approved.push(approval.kind);
  }
  return approved;
}

/**
 * Whether a list of approved effect kinds shows the lab actually **ran**
 * something.
 *
 * The one method claim this lane makes, and it is not fastidiousness about
 * process. Every published Project Euler answer is in a model's training data,
 * so "the company said 756872327473" is satisfied by recall — and a lane that
 * accepted recall would report green on a company whose sandbox, tool belt and
 * whole roster had stopped working. Requiring that a program was actually run
 * is what separates the claim "this company can solve problems" from "this
 * model has seen this problem".
 *
 * It is also the *only* thing separating them. Withholding the `web` grant
 * removes the obvious shortcut but closes no network — `shell` is granted and
 * there is no sandbox (`docs/spec/security/agent-isolation.md`) — so "it
 * cannot have looked the answer up" is not a claim this lane is entitled to
 * make. "It produced the answer by running something" is.
 *
 * Deliberately not stricter than that. *Which* teammate ran it, in what
 * language, after how many attempts, and whether the answer was also filed on a
 * ledger are all left alone.
 */
export function computed(approvedKinds: string[]): boolean {
  return approvedKinds.some((kind) => kind.includes("shell") || kind.includes("run_workflow"));
}
