// @generated by `cargo test -- --ignored regenerate_gated_tools` — do not edit.
//
// Every tool the runtime classifies as `Reach::Consequence` in
// `src/policy/consequence.rs`, which is exactly the set that parks for
// approval under the default `supervised` mode. `gated-tool-labels.test.ts`
// asserts each one resolves to plain language in `language.ts`, so a tool
// added to the Rust table cannot reach an operator unnamed (issue #706).
export const GATED_TOOLS = [
  "apply_patch",
  "composio_authorize",
  "csv_export",
  "curl",
  "edit",
  "file_write",
  "git_operations",
  "http_request",
  "mcp_call_tool",
  "mcp_registry_tool_call",
  "media_generate_image",
  "media_generate_video",
  "memory_store",
  "publish_artifact",
  "read_workspace_state",
  "run_workflow",
  "shell",
  "web_fetch",
  "workspace_create",
  "workspace_delete",
  "workspace_rename",
  "workspace_write",
] as const;
